# Generated by Django 3.2.25 on 2024-04-01 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('time_limit', models.IntegerField(default=0)),
                ('score_limit', models.IntegerField(default=0)),
                ('nb_players', models.IntegerField(default=0)),
                ('powerup', models.BooleanField(default=0)),
                ('player', models.CharField(max_length=100)),
                ('match', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('game_win', models.IntegerField(default=0)),
                ('game_lose', models.IntegerField(default=0)),
                ('game_draw', models.IntegerField(default=0)),
                ('game_abandon', models.IntegerField(default=0)),
                ('scored_point', models.IntegerField(default=0)),
                ('taken_point', models.IntegerField(default=0)),
                ('tournament_win', models.IntegerField(default=0)),
                ('tournament_played', models.IntegerField(default=0)),
                ('img_profile', models.ImageField(default='media/default.png', upload_to='')),
                ('p1Right', models.CharField(default='ArrowRight', max_length=20)),
                ('p1Left', models.CharField(default='ArrowLeft', max_length=20)),
                ('p1Shoot', models.CharField(default='Control', max_length=20)),
                ('p1Boost', models.CharField(default='Space', max_length=20)),
                ('p2Right', models.CharField(default='', max_length=20)),
                ('p2Left', models.CharField(default='', max_length=20)),
                ('p2Shoot', models.CharField(default='', max_length=20)),
                ('p2Boost', models.CharField(default='', max_length=20)),
                ('p3Right', models.CharField(default='', max_length=20)),
                ('p3Left', models.CharField(default='', max_length=20)),
                ('p3Shoot', models.CharField(default='', max_length=20)),
                ('p3Boost', models.CharField(default='', max_length=20)),
                ('p4Right', models.CharField(default='', max_length=20)),
                ('p4Left', models.CharField(default='', max_length=20)),
                ('p4Shoot', models.CharField(default='', max_length=20)),
                ('p4Boost', models.CharField(default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('time_limit', models.IntegerField(default=0)),
                ('score_limit', models.IntegerField(default=0)),
                ('player', models.IntegerField(default=2)),
                ('player_inlobby', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=1)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('player1', models.CharField(default='None', max_length=100)),
                ('player2', models.CharField(default='None', max_length=100)),
                ('player3', models.CharField(default='None', max_length=100)),
                ('player4', models.CharField(default='None', max_length=100)),
                ('player1_score', models.IntegerField(default=0)),
                ('player1_take', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('player2_take', models.IntegerField(default=0)),
                ('player3_score', models.IntegerField(default=0)),
                ('player3_take', models.IntegerField(default=0)),
                ('player4_score', models.IntegerField(default=0)),
                ('player4_take', models.IntegerField(default=0)),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('winner', models.CharField(max_length=100)),
                ('in_game', models.BooleanField(default=False)),
                ('is_single', models.BooleanField(default=False)),
                ('powerup', models.BooleanField(default=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pageloader.tournament')),
            ],
        ),
    ]
