# Generated by Django 4.2.16 on 2024-12-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ballCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player1_keyPressCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_keyPressCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
