# Generated by Django 4.2.17 on 2024-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ballCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player1_keyPressCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_keyPressCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='time_left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
