# Generated by Django 3.2.25 on 2024-04-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0003_alter_userprofile_img_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='requests',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_friend_list',
            field=models.ManyToManyField(blank=True, related_name='_pageloader_userprofile_user_friend_list_+', to='pageloader.UserProfile'),
        ),
    ]
