# Generated by Django 4.2.17 on 2025-01-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0004_game_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isinvitable',
            field=models.BooleanField(default=True),
        ),
    ]
