# Generated by Django 4.2.13 on 2024-05-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0004_auto_20240410_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_friend_list',
            field=models.ManyToManyField(blank=True, to='pageloader.userprofile'),
        ),
    ]
