# Generated by Django 4.2.17 on 2025-01-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0005_game_isinvitable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='isinvitable',
        ),
    ]
