# Generated by Django 4.2.13 on 2024-06-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0005_alter_userprofile_user_friend_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player',
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.IntegerField(default=0),
        ),
    ]
