# Generated by Django 4.2.13 on 2024-06-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0006_remove_game_player_game_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_single',
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(default='not_started', max_length=100),
        ),
    ]
