# Generated by Django 4.2.13 on 2024-06-09 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pageloader', '0007_remove_game_is_single_tournament_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='score_limit',
            new_name='limit',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='scored_point',
            new_name='tournament_abandon',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='taken_point',
            new_name='tournament_draw',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1_take',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_take',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player3_take',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player4_take',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='match',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='player',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='powerup',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='tournament',
            name='balls',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='boost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='games',
            field=models.ManyToManyField(related_name='tournaments', to='pageloader.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='games_structure',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.CharField(default='Time', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='game_played',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='pageloader.game'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tournament_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_player3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_player4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='game',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2',
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tournament_played',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='pageloader.tournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ManyToManyField(related_name='games_team1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ManyToManyField(related_name='games_team2', to=settings.AUTH_USER_MODEL),
        ),
    ]
