# Generated by Django 4.2.13 on 2024-06-09 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pageloader', '0011_alter_game_balls_alter_game_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='game_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
