# Generated by Django 4.2.13 on 2024-06-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0012_game_player_limit_remove_game_players_game_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='requests',
            new_name='pending_requests',
        ),
    ]
