# Generated by Django 4.2.13 on 2024-06-10 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pageloader', '0013_rename_requests_userprofile_pending_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ready_players',
            field=models.ManyToManyField(blank=True, related_name='ready_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
