# Generated by Django 4.2.13 on 2024-06-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0014_game_ready_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='in_game',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='not_started', max_length=100),
        ),
    ]
