# Generated by Django 4.2.13 on 2024-06-27 15:02

from django.db import migrations, models
import pageloader.models


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0016_remove_userprofile_pending_requests_pendingrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='img_profile',
            field=models.ImageField(default='profiles/default.png', upload_to=pageloader.models.user_directory_path),
        ),
    ]
