# Generated by Django 4.2.13 on 2024-08-03 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pageloader', '0017_alter_pendingrequest_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='games_structure',
            new_name='rounds_structure',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='games',
        ),
        migrations.AddField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='ready_players',
            field=models.ManyToManyField(blank=True, related_name='game_ready_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('rules', models.CharField(default='Time', max_length=100)),
                ('limit', models.IntegerField(blank=True, default=0, null=True)),
                ('balls', models.IntegerField(blank=True, default=1, null=True)),
                ('boost', models.BooleanField(default=True)),
                ('player_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('player_inlobby', models.IntegerField(blank=True, default=0, null=True)),
                ('player_scores', models.JSONField(default=dict)),
                ('team_scores', models.JSONField(default=dict)),
                ('status', models.CharField(default='not_started', max_length=100)),
                ('players', models.ManyToManyField(related_name='round_players', to=settings.AUTH_USER_MODEL)),
                ('ready_players', models.ManyToManyField(blank=True, related_name='round_ready_players', to=settings.AUTH_USER_MODEL)),
                ('team1', models.ManyToManyField(blank=True, related_name='rounds_team1', to=settings.AUTH_USER_MODEL)),
                ('team2', models.ManyToManyField(blank=True, related_name='rounds_team2', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pageloader.tournament')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds',
            field=models.ManyToManyField(related_name='tournaments', to='pageloader.round'),
        ),
    ]
