# Generated by Django 4.2.13 on 2024-09-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0019_tournament_players_in_lobby_tournament_slot_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_status',
            field=models.CharField(default='not_ready', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_status',
            field=models.CharField(default='not_ready', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='player3_status',
            field=models.CharField(default='not_ready', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='player4_status',
            field=models.CharField(default='not_ready', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='pageloader.userprofile'),
        ),
    ]
