# Generated by Django 4.2.13 on 2024-09-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0020_game_player1_status_game_player2_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='in_game_lobby',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_players', to='pageloader.game'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='in_tournament_lobby',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_players', to='pageloader.tournament'),
        ),
    ]
