# Generated by Django 4.2.16 on 2024-09-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0022_alter_game_player1_alter_game_player2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='in_game_lobby',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobby_players', to='pageloader.game'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='in_tournament_lobby',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobby_players', to='pageloader.tournament'),
        ),
    ]
