# Generated by Django 4.2.16 on 2024-10-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0023_alter_userprofile_in_game_lobby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='balls',
        ),
        migrations.RemoveField(
            model_name='round',
            name='boost',
        ),
        migrations.RemoveField(
            model_name='round',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='round',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='round',
            name='name',
        ),
        migrations.RemoveField(
            model_name='round',
            name='player_inlobby',
        ),
        migrations.RemoveField(
            model_name='round',
            name='player_limit',
        ),
        migrations.RemoveField(
            model_name='round',
            name='player_scores',
        ),
        migrations.RemoveField(
            model_name='round',
            name='players',
        ),
        migrations.RemoveField(
            model_name='round',
            name='ready_players',
        ),
        migrations.RemoveField(
            model_name='round',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='round',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='round',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='round',
            name='team_scores',
        ),
        migrations.RemoveField(
            model_name='round',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='rounds_structure',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='slot_status',
        ),
        migrations.AddField(
            model_name='round',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='games',
            field=models.ManyToManyField(related_name='round_games', to='pageloader.game'),
        ),
        migrations.AddField(
            model_name='round',
            name='ready_status',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='round',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='round',
            name='slots',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='round',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_rounds', to='pageloader.tournament'),
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='rounds',
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds',
            field=models.IntegerField(default=0),
        ),
    ]
