# Generated by Django 4.2.16 on 2024-11-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageloader', '0024_remove_round_balls_remove_round_boost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_hit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_hit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
